enum ActionTypeKeys {
    ADD_USER_REQUEST = 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS = 'ADD_USER_SUCCESS',
    ADD_USER_ERROR = 'ADD_USER_ERROR',
    ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST',
    ADD_PERSON = 'ADD_PERSON',
    ADD_PERSON_ERROR = 'ADD_PERSON_ERROR',
    ADD_WEIGHT_REQUEST = 'ADD_WEIGHT_REQUEST',
    ADD_WEIGHT = 'ADD_WEIGHT',
    ADD_WEIGHT_ERROR = 'ADD_WEIGHT_ERROR',
    REQUEST_USER = 'REQUEST_USER',
    RECEIVE_USER = 'RECEIVE_USER',
    ERROR_RECEIVING_USER = 'ERROR_RECEIVING_USER',
    REQUEST_PEOPLE = 'REQUEST_PEOPLE',
    RECEIVE_PEOPLE = 'RECEIVE_PEOPLE',
    ERROR_RECEIVING_PEOPLE = 'ERROR_RECEIVING_PEOPLE',
    REQUEST_PERSON = 'REQUEST_PERSON',
    RECEIVE_PERSON = 'RECEIVE_PERSON',
    ERROR_RECEIVING_PERSON = 'ERROR_RECEIVING_PERSON'
}

export default ActionTypeKeys;