enum ActionTypeKeys {
    REQUEST_PEOPLE = 'REQUEST_PEOPLE',
    RECEIVE_PEOPLE = 'RECEIVE_PEOPLE',
    ERROR_RECEIVING_PEOPLE = 'ERROR_RECEIVING_PEOPLE',
    REQUEST_PERSON = 'REQUEST_PERSON',
    RECEIVE_PERSON = 'RECEIVE_PERSON',
    ERROR_RECEIVING_PERSON = 'ERROR_RECEIVING_PERSON'
}

export default ActionTypeKeys;